version: 1.0.{build}

image: Visual Studio 2019

platform:
  - x64

configuration: Release

build_script:
  - cmd: >
      pip install pyinstaller
      pip install -r requirements.txt
      pyinstaller main.spec

artifacts:
  - path: dist\game.exe
    name: game-exe
