version: 1.0.{build}

image: Visual Studio 2019

platform:
  - x64

configuration: Release

environment:
  matrix:
    - PYTHON: "C:\\Python39" # Specify a compatible Python version (3.9 in this case)

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install pyinstaller"
  - "%PYTHON%\\python.exe -m pip install numpy pygame pillow utils"
  - set PATH=%PYTHON%\\Scripts;%PATH%

build_script:
  - cmd: >
      %PYTHON%\\python.exe -m pyinstaller main.spec

artifacts:
  - path: dist\game.exe
    name: game-exe
