version: 1.0.{build}

image: Visual Studio 2019

configuration: Release

environment:
  PYTHON: "C:\\Python39"

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - pip install -r requirements.txt
  - pip install pyinstaller

build_script:
  - pyinstaller main.spec

artifacts:
  - path: dist\*
    name: Executables
